import type { Metadata } from "next";
import { monsterrat } from './fonts'

import "./globals.css";


export const metadata: Metadata = {
  title: "BuilderZ",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" >
      <body className={monsterrat.className}>
        <div>{children}</div>
      </body>
    </html>
  )
}
